<html>
<head>
    <link rel="stylesheet" type="text/css" href="/smvc/skin/default/css/styles.css">
</head>
<body>
    <div class="wrapper">
        Body
        <?php echo Smvc::getRootDirPath()?>
        <?php echo Smvc::getDirPath("app")?>
        <?php echo $this->getTheme()->getBlock('header')?>
        <?php
            $var = "trt";
            Smvc::dump($var);
        ?>
        <?php echo Smvc::getConfig("database", "user");?>
    </div>
</body>
</html>
