<html>
<head>
    <?php echo $this->getBlock('scripts'); ?>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <?php echo $this->getBlock('header'); ?>
        </div>
        <div id="content">
            <?php echo $this->getContent(); ?>
        </div>
        <div id="footer">
            <?php echo $this->getBlock('footer'); ?>
        </div>
    </div>
</body>
</html>
