<div id="main-content">
    1.) Test form submitting:
    <form method="post" action="<?php echo $this->getRequest()->getUrl("index/index")?>">
        <table>
            <tr>
                <td>Name: </td>
                <td><input type="text" name="name" value="" placeholder="Your name" /></td>
            </tr>
            <tr>
                <td></td>
                <td>Mr.<input type="radio" name="title" value="Mr." checked></td>
            </tr>
            <tr>
                <td></td>
                <td>Ms.<input type="radio" name="title" value="Ms."></td>
            </tr>
        </table>
        <input type="submit" value="Click" />
    </form>
    <br/><br/>
    2.) <a href="<?php echo $this->getRequest()->getUrl("index/index/name/John/title/Mr.")?>">==Test setting params==</a>
    <br/><br/>
    3.) <a href="<?php echo $this->getRequest()->getUrl("bad/request")?>">==Test 404 handling==</a>
</div>